bsd:
  vars:
    ansible_python_interpreter: /usr/local/bin/python3
    # daily driver essentials :)
    packages:
      - curl
      - doas
      - freecolor
      - fzf
      - git
      - gmake
      - neovim
      - postfix
      - ripgrep
      - starship
      - tmux
      - wget
      - zoxide
      - zsh
  hosts: CHANGE-THIS-OF-COURSE.compute.amazonaws.com
